In [1]:
import numpy as np

np.linspace(-7, 7, 100)

array([-7.        , -6.85858586, -6.71717172, -6.57575758, -6.43434343,
       -6.29292929, -6.15151515, -6.01010101, -5.86868687, -5.72727273,
       -5.58585859, -5.44444444, -5.3030303 , -5.16161616, -5.02020202,
       -4.87878788, -4.73737374, -4.5959596 , -4.45454545, -4.31313131,
       -4.17171717, -4.03030303, -3.88888889, -3.74747475, -3.60606061,
       -3.46464646, -3.32323232, -3.18181818, -3.04040404, -2.8989899 ,
       -2.75757576, -2.61616162, -2.47474747, -2.33333333, -2.19191919,
       -2.05050505, -1.90909091, -1.76767677, -1.62626263, -1.48484848,
       -1.34343434, -1.2020202 , -1.06060606, -0.91919192, -0.77777778,
       -0.63636364, -0.49494949, -0.35353535, -0.21212121, -0.07070707,
        0.07070707,  0.21212121,  0.35353535,  0.49494949,  0.63636364,
        0.77777778,  0.91919192,  1.06060606,  1.2020202 ,  1.34343434,
        1.48484848,  1.62626263,  1.76767677,  1.90909091,  2.05050505,
        2.19191919,  2.33333333,  2.47474747,  2.61616162,  2.75

In [2]:
nx, ny = (5, 3)
print( "Number of x's:", nx )
print( "Number of y's:", ny )

# We create an x-axis with a total of 'nx' marks along it
x = np.linspace(0, 1, nx)
# We create an y-axis with a total of 'ny' marks along it
y = np.linspace(0, 1, ny)

# We now create two matrices, which we will create with 'xy' reference coordinate system
xv, yv = np.meshgrid(x, y)
print( "xv shape: %s %s \n" % xv.shape, xv  )
print( "yv shape: %s %s \n" % yv.shape, yv )
print( "\nAnd now its rotated version, 90º clockwise if changing from an xy layout to an ij layout" )

# And now another two matrices, which we will create with 'xy' reference coordinate system
iv, jv = np.meshgrid(x, y, indexing = 'ij' )
print( "iv shape: %s %s \n" % iv.shape, iv  )
print( "jv shape: %s %s \n" % jv.shape, jv )



Number of x's: 5
Number of y's: 3
xv shape: 3 5 
 [[0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]
 [0.   0.25 0.5  0.75 1.  ]]
yv shape: 3 5 
 [[0.  0.  0.  0.  0. ]
 [0.5 0.5 0.5 0.5 0.5]
 [1.  1.  1.  1.  1. ]]

And now its rotated version, 90º clockwise if changing from an xy layout to an ij layout
iv shape: 5 3 
 [[0.   0.   0.  ]
 [0.25 0.25 0.25]
 [0.5  0.5  0.5 ]
 [0.75 0.75 0.75]
 [1.   1.   1.  ]]
jv shape: 5 3 
 [[0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]
 [0.  0.5 1. ]]
